### PR TITLE
Fixed setup of wsdl files

### PR DESCRIPTION
**Pull request by karlkar**
Hello.
This fix is related to issue #13 
After applying it wsdls will be installed in proper place:
lib/python<proper_version>/site-packages/onvif_zeep-<version>-py<version>.egg/onvif

### CODE REVIEW

**Comment by hakan458** [comment]
Why was this closed?

**Comment by LichtiMC** [comment]
still a problem on current systems

**Comment by CDahmsCellarEye** [comment]
I'm having this problem as well:

```
$ python3 test1.py 
Traceback (most recent call last):
  File "test1.py", line 14, in <module>
    main()
  File "test1.py", line 7, in main
    camera = ONVIFCamera('192.168.1.175', 80, 'admin', 'pass')
  File "/usr/local/lib/python3.6/dist-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 215, in __init__
    self.update_xaddrs()
  File "/usr/local/lib/python3.6/dist-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 222, in update_xaddrs
    self.devicemgmt = self.create_devicemgmt_service()
  File "/usr/local/lib/python3.6/dist-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 343, in create_devicemgmt_service
    return self.create_onvif_service('devicemgmt', transport=transport)
  File "/usr/local/lib/python3.6/dist-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 320, in create_onvif_service
    xaddr, wsdl_file, binding_name = self.get_definition(name, portType)
  File "/usr/local/lib/python3.6/dist-packages/onvif_zeep-0.2.12-py3.6.egg/onvif/client.py", line 291, in get_definition
    raise ONVIFError('No such file: %s' % wsdlpath)
onvif.exceptions.ONVIFError: Unknown error: No such file: /usr/local/lib/python3.6/dist-packages/onvif_zeep-0.2.12-py3.6.egg/wsdl/devicemgmt.wsdl
```

**Comment by mweinelt** [comment]
Probably because it was like that before and was changed for Windows support
https://github.com/FalkTannhaeuser/python-onvif-zeep/commit/4691372c094c159e38cb025d41de37cd44caa270

**Pull request closed without merging**
